package com.jspider.servlet1.myservlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class MyServlet1 extends HttpServlet {
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		resp.setContentType("text/html");
		PrintWriter writer = resp.getWriter();
		writer.println("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>NoBroker</title>\r\n"
				+ "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n"
				+ "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap\" rel=\"stylesheet\">\r\n"
				+ "    <style>\r\n"
				+ "        * {\r\n"
				+ "            margin: 0;\r\n"
				+ "            padding: 0;\r\n"
				+ "            box-sizing: border-box;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        body {\r\n"
				+ "            font-family: 'Source Sans Pro', sans-serif;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #nav {\r\n"
				+ "            font-weight: bold;\r\n"
				+ "            height: 80px;\r\n"
				+ "            width: 100%;\r\n"
				+ "            border: 1px solid red;\r\n"
				+ "            /* position: fixed; */\r\n"
				+ "            display: flex;\r\n"
				+ "            gap: 5px;\r\n"
				+ "            flex-direction: row;\r\n"
				+ "            justify-content: space-between;\r\n"
				+ "            padding: 20px;\r\n"
				+ "            margin: auto;\r\n"
				+ "            box-shadow: 100px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #nbroker {\r\n"
				+ "            margin: auto;\r\n"
				+ "            margin-left: 0px;\r\n"
				+ "            margin-bottom: 60px;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #log {\r\n"
				+ "            display: flex;\r\n"
				+ "            justify-content: center;\r\n"
				+ "            align-items: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .box {\r\n"
				+ "            height: auto;\r\n"
				+ "            width: auto;\r\n"
				+ "            border: 1px solid;\r\n"
				+ "            display: flex;\r\n"
				+ "            margin: auto;\r\n"
				+ "            padding: 5px;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #bookingimg {\r\n"
				+ "            display: inline;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #box1 {\r\n"
				+ "            height: 30px;\r\n"
				+ "            width: 140px;\r\n"
				+ "            text-align: center;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #box3 {\r\n"
				+ "\r\n"
				+ "            width: 150px;\r\n"
				+ "            text-align: center;\r\n"
				+ "            background-color: #07a094;\r\n"
				+ "            color: #fff;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #box4 {\r\n"
				+ "            border: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #box5 {\r\n"
				+ "            border: none;\r\n"
				+ "            border-left: 1px solid;\r\n"
				+ "            border-right: 1px solid;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #box6 {\r\n"
				+ "            border: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #head {\r\n"
				+ "            text-align: center;\r\n"
				+ "            margin-top: 60px;\r\n"
				+ "            color: rgb(252, 22, 60);\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #main {\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "            border: 1px solid yellow;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #paint {\r\n"
				+ "            width: 250px;\r\n"
				+ "            height: auto;\r\n"
				+ "            border: 1px solid;\r\n"
				+ "            padding: 5px;\r\n"
				+ "            margin: 25px auto;\r\n"
				+ "            background-color: rgb(244, 211, 216);\r\n"
				+ "            /* margin-top: 25px; */\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #buy {\r\n"
				+ "            width: 100vw;\r\n"
				+ "            height: 100%;\r\n"
				+ "            /* border: 1px solid; */\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "            display: flex;\r\n"
				+ "            justify-content: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "        .boxs {\r\n"
				+ "            width: 130px;\r\n"
				+ "            height: 40px;\r\n"
				+ "            border: 1px solid gray;\r\n"
				+ "            color: gray;\r\n"
				+ "            text-align: center;\r\n"
				+ "            padding: 10px 15px;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #state {\r\n"
				+ "            width: 120px;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #search {\r\n"
				+ "            height: 100%;\r\n"
				+ "            width: 1000px;\r\n"
				+ "            /* border: 1px solid; */\r\n"
				+ "            /* margin: 0 auto;\r\n"
				+ "             */\r\n"
				+ "            margin-left: 500px;\r\n"
				+ "            display: inline-block;\r\n"
				+ "            display: flex;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .parent {\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "            border: 2px solid red;\r\n"
				+ "            /* flex-direction: column; */\r\n"
				+ "            /* justify-content: start; */\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #searchip {\r\n"
				+ "            width: 400px;\r\n"
				+ "            height: 40px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #state {\r\n"
				+ "            height: 40px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #search1 {\r\n"
				+ "            height: 40px;\r\n"
				+ "            width: 50px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #radio {\r\n"
				+ "            display: flex;\r\n"
				+ "            justify-content: center;\r\n"
				+ "            align-items: center;\r\n"
				+ "            gap: 5px;\r\n"
				+ "            width: 500px;\r\n"
				+ "            height: 40px;\r\n"
				+ "            border: 1px solid;\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "            padding: 15px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        h4 {\r\n"
				+ "            margin-top: 40px;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #property {\r\n"
				+ "            width: 200px;\r\n"
				+ "            height: 45px;\r\n"
				+ "            border: 1px solid;\r\n"
				+ "            margin: 20px auto;\r\n"
				+ "            padding: 12px;\r\n"
				+ "            text-align: center;\r\n"
				+ "            background-color: rgb(196, 131, 141);\r\n"
				+ "            color: white;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #pay {\r\n"
				+ "            color: white;\r\n"
				+ "            width: 100%;\r\n"
				+ "            height: 60px;\r\n"
				+ "            background-color: rgb(4, 4, 87);\r\n"
				+ "            text-align: center;\r\n"
				+ "            padding: 20px;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #pr {\r\n"
				+ "            gap: 10px;\r\n"
				+ "            margin-top: 30px;\r\n"
				+ "            display: flex;\r\n"
				+ "            justify-content: center;\r\n"
				+ "            align-items: center;\r\n"
				+ "            width: 100%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        hr {\r\n"
				+ "            border: none;\r\n"
				+ "            border-bottom: 1px solid grey;\r\n"
				+ "            display: inline-block;\r\n"
				+ "            width: 30px;\r\n"
				+ "\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "    <nav id=\"nav\">\r\n"
				+ "        <div id=\"nbroker\"><img id=\"nbimg\" src=\"./Image/nb_logo_new_trans.svg\" alt=\"\"></div>\r\n"
				+ "        <div id=\"log\">\r\n"
				+ "            <div class=\"box\" id=\"box1\"><img id=\"bookingimg\" src=\"./Image/myBooking.svg\" alt=\"\"> My Bookings</div>\r\n"
				+ "            <div class=\"box\" id=\"box2\"><img src=\"./Image/payrent.png\" alt=\"\"> Pay Rent</div>\r\n"
				+ "            <div class=\"box\" id=\"box3\">For Property Owners</div>\r\n"
				+ "            <div class=\"box\" id=\"box4\">Sign Up</div>\r\n"
				+ "            <div class=\"box\" id=\"box5\">Log In</div>\r\n"
				+ "            <div class=\"box\" id=\"box6\">Menu</div>\r\n"
				+ "        </div>\r\n"
				+ "    </nav>\r\n"
				+ "    <div class=\"parent\">\r\n"
				+ "        <div id=\"main\">\r\n"
				+ "            <h1 id=\"head\">World's Largest NoBrokerage Property Site</h1>\r\n"
				+ "            <div id=\"paint\">Painting and Cleaning| Upto 50%Off</div>\r\n"
				+ "            <div id=\"buy\">\r\n"
				+ "                <div class=\"boxs\">Buy</div>\r\n"
				+ "                <div class=\"boxs\" id=\"rent\">Rent</div>\r\n"
				+ "                <div class=\"boxs\">Commercial</div>\r\n"
				+ "            </div>\r\n"
				+ "            <div id=\"search\">\r\n"
				+ "                <select name=\"\" id=\"state\">\r\n"
				+ "                    <option value=\"\">Banglore</option>\r\n"
				+ "                    <option value=\"\">Pune</option>\r\n"
				+ "                    <option value=\"\">Chennai</option>\r\n"
				+ "                </select>\r\n"
				+ "                <input id=\"searchip\" type=\"text\" placeholder=\"Search upto 3 localities or landmarks\">\r\n"
				+ "                <button id=\"search1\">Search</button>\r\n"
				+ "            </div>\r\n"
				+ "            <div id=\"radio\">\r\n"
				+ "                <input type=\"radio\" name=\"full house\" id=\"full house\">full house <input type=\"radio\" name=\"\"\r\n"
				+ "                    id=\"\">PG/Hostels <input type=\"radio\" name=\"\" id=\"\">Flatmates\r\n"
				+ "                <select name=\"BHK\" id=\"BHK\">BHK Type\r\n"
				+ "                    <option value=\"none\" selected>BHK Type</option>\r\n"
				+ "                    <!-- <input type=\"checkbox\" name=\"\" id=\"\"> -->\r\n"
				+ "                    <option value=\"\">1RK</option>\r\n"
				+ "                    <option value=\"\">1BHK</option>\r\n"
				+ "                </select>\r\n"
				+ "\r\n"
				+ "                <select name=\"\" id=\"available\">\r\n"
				+ "                    <option value=\"none\">Avaibility</option>\r\n"
				+ "                    <option value=\"\">10days</option>\r\n"
				+ "                    <option value=\"\">20days</option>\r\n"
				+ "                </select>\r\n"
				+ "\r\n"
				+ "            </div>\r\n"
				+ "            <div id=\"pr\">\r\n"
				+ "                <hr>\r\n"
				+ "                <span>Are You Property Owner?</span>\r\n"
				+ "                <hr>\r\n"
				+ "            </div>\r\n"
				+ "            <div id=\"property\">Post Free Property Ad?</div>\r\n"
				+ "            <nav id=\"pay\"><b> Maintenance and Rent with Credit Card!</b></nav>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>");
		writer.close();
		
	}

}
